Repository apple/swift-asn1, pull requests merged in 2024-10, with the labels that each got.

#68 Add support for CRLF line endings to `PEMDocument`
  Sources/SwiftASN1/Basic ASN1 Types/PEMDocument.swift
  Tests/SwiftASN1Tests/ASN1Tests.swift
Labels: semver/patch

#73 Fixes to yaml to satisfy linter
  .github/workflows/pull_request.yml
  docker/docker-compose.2204.60.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.yaml
Labels: semver/none

#72 More Sendability annotiations
  Sources/SwiftASN1/ASN1.swift
  Sources/SwiftASN1/BER.swift
  Sources/SwiftASN1/Basic ASN1 Types/ObjectIdentifier.swift
  Sources/SwiftASN1/Basic ASN1 Types/TimeUtilities.swift
  Sources/SwiftASN1/DER.swift
Labels: semver/patch

#69 Drop Swift 5.8
  Benchmarks/Package.swift
  Package.swift
  docker/docker-compose.2204.58.yaml
Labels: semver/minor

#74 Migrate to GitHub Actions reusable workflows (2)
  .github/workflows/pull_request.yml
  .github/workflows/pull_request_label.yml
  Benchmarks/Thresholds/6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument_.p90.json
  Benchmarks/Thresholds/nightly-6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/nightly-6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/nightly-6.0/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument_.p90.json
  Benchmarks/Thresholds/nightly-main/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/nightly-main/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument.p90.json
  Benchmarks/Thresholds/nightly-main/SwiftASN1Benchmark.Parse_WebPKI_Roots_from_multi_PEM_to_PEMDocument_.p90.json
  CONTRIBUTING.md
  Package.swift
  Sources/SwiftASN1/ASN1.swift
  Sources/SwiftASN1/BER.swift
  Sources/SwiftASN1/Basic ASN1 Types/TimeUtilities.swift
  Sources/SwiftASN1/DER.swift
  dev/update-benchmark-thresholds.sh
  docker/docker-compose.yaml
  scripts/check_no_api_breakages.sh
  scripts/run-swift-format.sh
  scripts/soundness.sh
  scripts/update_cmakelists.sh
Labels: semver/none

#75 Remove legacy CI docker/script files
  docker/Dockerfile
  docker/docker-compose.2204.510.yaml
  docker/docker-compose.2204.59.yaml
  docker/docker-compose.2204.60.yaml
  docker/docker-compose.2204.main.yaml
  docker/docker-compose.yaml
  scripts/check_no_api_breakages.sh
Labels: semver/none

#76 CI: concurrency=complete require-explicit-sendable
  .github/workflows/pull_request.yml
  .github/workflows/scheduled.yml
  Package.swift
Labels: semver/none

#78 Remove script for updating contributors list
  scripts/generate_contributors_list.sh
Labels: semver/none
